FROM php:8.2-apache

# 1. Install dependencies for Curl and APCu
RUN apt-get update && apt-get install -y \
    git \
    libxml2-dev \
    libonig-dev \
    libcurl4-openssl-dev \
    && docker-php-ext-install dom xml mbstring curl \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && a2enmod rewrite \
    && apt-get install -y tini \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

# Create dummy lib to prevent 4get from loading real backend/fuckhtml
RUN mkdir -p dummy_lib/lib && \
    touch dummy_lib/lib/backend.php && \
    touch dummy_lib/lib/fuckhtml.php

COPY src/ /var/www/html/
COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

# Use tini to manage the process headers
ENTRYPOINT ["/usr/bin/tini", "--", "entrypoint.sh"]
CMD ["apache2-foreground"]